### ISSUE TITLE
Reference to undefined setting

### ISSUE THREAD

**Issue by Tolsi** [sbt/sbt-javaagent#5]
I added `addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent" % "0.1.1")` to project/plugins.sbt, then I added `javaAgents += "sbt.javaagent.test" % "maxwell" % sys.props("project.version") % "runtime"` to my build.sbt and I have error:
```
Reference to undefined setting:

  *:javaAgents from *:javaAgents (..../build.sbt:98)

       	at sbt.Init$class.Uninitialized(Settings.scala:265)
       	at sbt.Def$.Uninitialized(Def.scala:10)
       	at sbt.Init$class.delegate(Settings.scala:191)
       	at sbt.Def$.delegate(Def.scala:10)
       	at sbt.Init$class.compiled(Settings.scala:138)
       	at sbt.Def$.compiled(Def.scala:10)
       	at sbt.Init$class.make(Settings.scala:144)
       	at sbt.Def$.make(Def.scala:10)
       	at sbt.Load$.apply(Load.scala:135)
       	at sbt.Load$.defaultLoad(Load.scala:36)
       	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
       	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
       	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
       	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
       	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
       	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
       	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
       	at sbt.Command$.process(Command.scala:92)
       	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
       	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
       	at sbt.State$$anon$1.process(State.scala:184)
       	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
       	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
       	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
       	at sbt.MainLoop$.next(MainLoop.scala:98)
       	at sbt.MainLoop$.run(MainLoop.scala:91)
       	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
       	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
       	at sbt.Using.apply(Using.scala:24)
       	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
       	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
       	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
       	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
       	at sbt.StandardMain$.runManaged(Main.scala:53)
       	at sbt.xMain.run(Main.scala:28)
       	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
       	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
       	at xsbt.boot.Launch$.run(Launch.scala:109)
       	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
       	at xsbt.boot.Launch$.launch(Launch.scala:117)
       	at xsbt.boot.Launch$.apply(Launch.scala:18)
       	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
       	at xsbt.boot.Boot$.main(Boot.scala:17)
       	at xsbt.boot.Boot.main(Boot.scala)
```

but I see it in `plugins`:
```
[chat backend] $ plugins
In file:/Users/tolsi/Documents/rubl/clustered-chat/
       	sbt.plugins.IvyPlugin: enabled in root
       	sbt.plugins.JvmPlugin: enabled in root
       	sbt.plugins.CorePlugin: enabled in root
       	sbt.plugins.JUnitXmlReportPlugin: enabled in root
       	play.sbt.Play: enabled in root
       	play.sbt.PlayAkkaHttpServer
       	play.sbt.PlayJava
       	play.sbt.PlayLayoutPlugin: enabled in root
       	play.sbt.PlayLogback: enabled in root
       	play.sbt.PlayNettyServer: enabled in root
       	play.sbt.PlayScala: enabled in root
       	play.sbt.routes.RoutesCompiler: enabled in root
       	play.twirl.sbt.SbtTwirl: enabled in root
       	com.typesafe.sbt.SbtNativePackager: enabled in root
       	com.typesafe.sbt.packager.archetypes.AkkaAppPackaging
       	com.typesafe.sbt.packager.archetypes.AshScriptPlugin
       	com.typesafe.sbt.packager.archetypes.JavaAppPackaging: enabled in root
       	com.typesafe.sbt.packager.archetypes.JavaServerAppPackaging: enabled in root
       	com.typesafe.sbt.packager.archetypes.jar.ClasspathJarPlugin
       	com.typesafe.sbt.packager.archetypes.jar.LauncherJarPlugin
       	com.typesafe.sbt.packager.debian.DebianDeployPlugin
       	com.typesafe.sbt.packager.debian.DebianPlugin: enabled in root
       	com.typesafe.sbt.packager.debian.JDebPackaging: enabled in root
       	com.typesafe.sbt.packager.docker.DockerPlugin: enabled in root
       	com.typesafe.sbt.packager.docker.DockerSpotifyClientPlugin
       	com.typesafe.sbt.packager.jdkpackager.JDKPackagerDeployPlugin
       	com.typesafe.sbt.packager.jdkpackager.JDKPackagerPlugin
       	com.typesafe.sbt.packager.linux.LinuxPlugin: enabled in root
       	com.typesafe.sbt.packager.rpm.RpmDeployPlugin
       	com.typesafe.sbt.packager.rpm.RpmPlugin: enabled in root
       	com.typesafe.sbt.packager.universal.UniversalDeployPlugin
       	com.typesafe.sbt.packager.universal.UniversalPlugin: enabled in root
       	com.typesafe.sbt.packager.windows.WindowsDeployPlugin
       	com.typesafe.sbt.packager.windows.WindowsPlugin: enabled in root
       	com.typesafe.sbt.web.SbtWeb: enabled in root
       	com.typesafe.sbt.jse.SbtJsEngine: enabled in root
       	com.typesafe.sbt.jse.SbtJsTask: enabled in root
       	net.virtualvoid.sbt.graph.DependencyGraphPlugin: enabled in root
       	com.lightbend.sbt.javaagent.JavaAgent
       	com.lightbend.sbt.javaagent.JavaAgentPackaging
```

my build.sbt:
```
// build me with "sbt clean debian:packageBin" and find deb in target folder

name := "..."

maintainer := "..."

packageSummary := "..."

packageDescription := """..."""

version := "..."

debianPackageDependencies in Debian ++= Seq("postgresql-9.5 (>= 9.5.1)")

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.8"

val akkaVersion = "2.4.9"

libraryDependencies ++= Seq(
  "org.postgresql" % "postgresql" % "9.4.1208",
  "org.scalikejdbc" %% "scalikejdbc" % "2.4.0",
  "org.scalikejdbc" %% "scalikejdbc-config" % "2.4.0",
  "org.scalikejdbc" %% "scalikejdbc-play-initializer" % "2.5.1",
  "org.flywaydb" %% "flyway-play" % "3.0.1",
  "com.typesafe.akka" %% "akka-contrib" % akkaVersion,
  "com.typesafe.akka" %% "akka-slf4j" % akkaVersion,
  "io.dropwizard.metrics" % "metrics-core" % "3.1.2",
  "io.dropwizard.metrics" % "metrics-jvm" % "3.1.2",
  "org.coursera" % "dropwizard-metrics-datadog" % "1.1.4",
  "org.vafer" % "jdeb" % "1.3" artifacts Artifact("jdeb", "jar", "jar"),
  "com.typesafe.akka" %% "akka-testkit" % akkaVersion % Test,
  "com.relayrides" % "pushy" % "0.8",
  "com.relayrides" % "pushy-dropwizard-metrics-listener" % "0.8",
  "org.eclipse.jetty.alpn" % "alpn-api" % "1.1.3.v20160715" % "runtime",
  specs2 % Test
)

resolvers += "Typesafe Releases" at "http://repo.typesafe.com/typesafe/maven-releases/"
resolvers += Resolver.mavenLocal

// Play provides two styles of routers, one expects its actions to be injected, the
// other, legacy style, acgjcesses its actions statically.
routesGenerator := InjectedRoutesGenerator

javaOptions in Test ++= Seq("-Dlogger.resource=logback-test.xml")

scalacOptions in Universal ++= Seq("-unchecked", "-deprecation", "-notailcalls")

javaOptions in Universal ++= Seq(
  // JVM memory tuning
  "-J-Xmx768m",
  "-J-Xms64m",

  "-J-verbose:gc",
  s"-J-Xloggc:/var/log/${packageName.value}/gc.log",
  "-J-XX:+PrintGCDetails",
  "-J-XX:+PrintGCTimeStamps",
  "-J-XX:+PrintGCApplicationStoppedTime",
  "-J-XX:+UseGCLogFileRotation",
  "-J-XX:NumberOfGCLogFiles=10",
  "-J-XX:GCLogFileSize=2M",

  // JMX
  "-J-Dcom.sun.management.jmxremote",
  "-J-Dcom.sun.management.jmxremote.port=9010",
  "-J-Dcom.sun.management.jmxremote.local.only=false",
  "-J-Dcom.sun.management.jmxremote.authenticate=false",
  "-J-Dcom.sun.management.jmxremote.ssl=false",

  // Since play uses separate pidfile we have to provide it with a proper path
  s"-Dpidfile.path=/var/run/${packageName.value}/play.pid",

  // Use separate configuration file for production environment
  s"-Dconfig.file=/usr/share/chat-backend/conf/production.conf",

  // Use separate logger configuration file for production environment
  s"-Dlogger.file=/usr/share/chat-backend/conf/production-logger.xml",

  // flyway auto migration
  "-Ddb.default.migration.auto=true",

  // http server params
  "-Dhttp.port=9000",
  "-Dhttp.address=0.0.0.0"
)

bashScriptExtraDefines += """addJava "-Djava.rmi.server.hostname=`curl -s http://whatismijnip.nl |cut -d " " -f 5`""""

enablePlugins(JDebPackaging)

javaAgents += "sbt.javaagent.test" % "maxwell" % sys.props("project.version") % "runtime"
```

**Comment by pvlugter** [comment]
Hi @Tolsi. Looks like you don't have the `JavaAgent` plugin enabled in your `build.sbt`. For example:

```scala
lazy val root = (project in file(".")).enablePlugins(PlayScala, JavaAgent)
```

**Comment by pvlugter** [comment]
Unless you've published the test agent (maxwell) somewhere and set the `project.version` property, you'll want to use an actual agent dependency.

**Comment by Tolsi** [comment]
oh, I missed it, thank you!
